name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - KitsueFox
body:
  - type: markdown
    attributes: 
      value: |
        Thanks for taking the time to fill out this bug report! Before Posting, please remove any other mods and isolate the Issue
  - type: checkboxes
    id: mods-affected
    attributes: 
      label: Mods Affected
      description: Please Select the mods that are casuing the bug.
      options:
        - label: Duck Trainer
        - label: Event Reenable
        - label: Custom Names
  - type: input
    id: what-happened
    attributes: 
      label: What Happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: melon-logs
    attributes: 
      label: Melonloader Latest.log
      description: Please copy and paste the melonloader log output. This is located "..\steamapps\common\Placid Plastic Duck Simulator\MelonLoader\Latest.log"
      render: shell
  - type: textarea
    id: game-logs
    attributes:
      label: PPDS Player.log
      description: Please copy and paste the Game log output. This is located "%appdata%\..\LocalLow\Turbolento Games\Placid Plastic Duck Simulator\Player.log"
      render: shell
  